name = "ambedkaritebuddhist"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding       = "DB"
database_name = "REPLACE_WITH_YOUR_DATABASE_NAME"
database_id   = "REPLACE_WITH_YOUR_DATABASE_ID"
migrations_dir = "migrations"
