ALTER TABLE Event ADD COLUMN showVolunteering INTEGER NOT NULL DEFAULT 1;
ALTER TABLE Event ADD COLUMN showCulturalVolunteering INTEGER NOT NULL DEFAULT 0;
ALTER TABLE Event ADD COLUMN showNeedsRide INTEGER NOT NULL DEFAULT 0;
ALTER TABLE Event ADD COLUMN showPhotoConsent INTEGER NOT NULL DEFAULT 1;
ALTER TABLE Event ADD COLUMN showDonation INTEGER NOT NULL DEFAULT 0;
ALTER TABLE Event ADD COLUMN showNotes INTEGER NOT NULL DEFAULT 0;
